/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Preprocessor information generated by a preprocessor node.
 */
export interface PreprocessorResponse {
  /**
   * UUID v4 identifying the request.
   */
  request_uuid: string;
  /**
   * Time the preprocessor was run in Unix time.
   */
  timestamp: number;
  /**
   * The unique reverse domain name identifier of the preprocessor that the data will be available under.
   */
  name: string;
  /**
   * The well-defined data produced by the preprocessor.
   */
  data: {
    /**
     * A URL that resolves to the JSON schema for the data property.
     */
    data_schema?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
