/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response of timestamped audio segments.
 */
export interface TTSSegmentResponse {
  /**
   * Data URL of the base64 wave file returned.
   */
  audio: string;
  /**
   * Duration of each segment in the audio file.
   */
  durations: number[];
  [k: string]: unknown;
}
