/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Request for a timestamped TTS audio from an array of segments.
 */
export interface TTSSegmentRequest {
  segments: string[];
  /**
   * A parameter controlling the speed of a synthesized voice. 1 is normal, lower values are faster, and higher values are slower.
   */
  speed_control_alpha?: number;
  [k: string]: unknown;
}
