/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data for the noninteractive audio renderer ca.mcgill.a11y.image.renderer.SimpleAudio.
 */
export type SimpleAudioRenderer =
  | {
      /**
       * HTTP(S) URL to an audio file.
       */
      audio: string;
      [k: string]: unknown;
    }
  | {
      /**
       * Data URI of an encoded audio file.
       */
      audio: string;
      [k: string]: unknown;
    };
