/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data for the plain text renderer ca.mcgill.cim.bach.atp.renderer.Text.
 */
export interface PlainTextRenderer {
  text: string;
  [k: string]: unknown;
}
