name: Bump version
on:
  push:
    branches:
      - version-bump
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      id: bump-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
    
    - name: set up env new_version
      run: echo "NEW_VERSION=$(echo ${{ steps.bump-version.outputs.new_tag }} | cut -c2-7)" >> $GITHUB_ENV
    
    - name: Override manifest with new version
      run: |
          echo 'New version ${{ env.NEW_VERSION }}'
          jq '.version = \"${{ env.NEW_VERSION }}\"' src/manifest.json