name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      id: bump-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
    
    - name: Override manifest with new version
      run: |
          newVersion = ${{ steps.bump-version.outputs.new_tag }}
          versionNumber = "${newVersion:1}"
          echo 'New version ${{ versionNumber }}'
          jq '.version = \"${{ versionNumber }}\"' src/manifest.json